<?php

namespace Sander\AdventOfCode;

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Logger\ConsoleLogger;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Contracts\EventDispatcher\EventDispatcherInterface;

final class Kernel extends Application
{
    protected string $env = 'prod';
    protected bool $debug = false;

    public const DEV_ENVIRONMENT = 'dev';
    public const PROD_ENVIRONMENT = 'prod';
    public const TEST_ENVIRONMENT = 'test';


    /**
     * Constructor.
     * @param iterable $commands
     * @param string $name
     * @param string $version
     * @param string $env
     * @param bool $debug
     */
    public function __construct(
        iterable $commands = [],
        string $name = 'UNKNOWN',
        string $version = 'UNKNOWN',
        string $env = self::DEV_ENVIRONMENT,
        bool $debug = true,
    ){
        foreach ($commands as $command) {
            $this->add($command);
        }

        $this->debug = $debug;
        $this->env = $env;

        parent::__construct($name, $version);
    }

    public function doRun(InputInterface $input, OutputInterface $output): int
    {
        Logger::set(new ConsoleLogger($output));
        return parent::doRun($input, $output); // TODO: Change the autogenerated stub
    }

    public function getEnv(): string
    {
        return $this->env;
    }

    public function getDebug(): bool
    {
        return $this->debug;
    }
}